In [1]:
using LinearAlgebra, Polyhedra, CDDLib
using JuMP, Ipopt, Clarabel
using Random
using PhyloNetworks

In [2]:
function trop_normalize(x)
    return x .- first(x)
end

trop_normalize (generic function with 1 method)

# Polyhedral point location

In [3]:
"""
Calculate the polyhedral distance between two vectors.
The rows of `alphas` are the facet normals scaled to α⋅x = 1.
"""
function poly_dist(vec1, vec2, alphas)
    differences = alphas * (vec1 - vec2)
    return maximum(differences)
end

poly_dist

In [4]:
"""
Calculate the sum of polyhedral distances between `ref` and the points in `sample`.
The rows of `alphas` are the facet normals scaled to α⋅x = 1.
`power` gives the exponent of the distance before taking the sum.
"""
function sum_of_poly_dist(ref, sample, alphas; power=1)
    return sum([poly_dist(pt, ref, alphas)^power for pt in sample])
end

sum_of_poly_dist

In [5]:
function poly_frechet_model(sample, alphas; power=2)
    dim = length(sample[1])
    
    # Choose model depending on power
    if power == 1
        error("FW computation not yet implemeneted")
    elseif power == 2
        model = Model(Clarabel.Optimizer)
    else
        model = Model(Ipopt.Optimizer)
    end
    
    # suppress printing
    set_silent(model)

    @variable(model, x[1:dim])
    @variable(model, t[1:length(sample)])

    @objective(model, Min, sum(t))

    for (p_idx, p) in enumerate(sample)
        expressions = alphas * (x - p)
        
        for expr in expressions
            @constraint(model, t[p_idx] >= (expr)^power)
        end
    end

    return model, x
end

poly_frechet_model (generic function with 1 method)

In [6]:
"""
Find one polyhedral Fréchet mean of a given sample.
The rows of `alphas` are the facet normals scaled to α⋅x = 1.
`power` gives the exponent of the distance before taking the sum.
"""
function poly_frechet(sample, alphas; power=2)
    model, x = poly_frechet_model(sample, alphas, power=power)
    
    @debug "\nOptimising..."
    
    optimize!(model)
    minimiser = value.(x)
    
    return minimiser
end

poly_frechet

In [7]:
"""
Find the set of polyhedral Fréchet means of a given sample.
The rows of `alphas` are the facet normals scaled to α⋅x = 1.
`power` gives the exponent of the distance before taking the sum.
`rep` is either "vrep" or "hrep" -- returning either vertices or halfspaces.
"""
function poly_frechet_set(::Type{T}, sample, alphas; power=2, rep=:polyhedron, tol=1e-3) where {T<:Polyhedra.Library}
    dim = length(sample[1])
    num_facets = size(alphas)[1]
    
    # Compute one Fréchet mean
    one_mean = poly_frechet(sample, alphas, power=power)
    
    @debug "Frechet mean found: $(one_mean)"
    
    # Rationalise all coordinates
    rat_alphas = rationalize.(alphas, tol=tol)
    rat_sample = [rationalize.(pt, tol=tol) for pt in sample]
    rat_mean = rationalize.(one_mean, tol=tol)
    
    distances = [poly_dist(rat_mean, pt, alphas) for pt in rat_sample]
    
    Amat = vcat(rat_alphas, -rat_alphas)
    bval1 = Rational{Int64}[]
    bval2 = Rational{Int64}[]
    
    # Discard redundant halfspacesprintln("Setting up constraints: $(round(progress/total * 100, digits=3))%   \r")
    evals = rat_alphas * hcat([rat_mean - pt for pt in rat_sample]...)
    for k in 1:length(rat_sample)
        evals[:,k] .-= distances[k]
    end
    
    progress = 0
    total = num_facets
    
    for k = 1:num_facets
        
        greatest_nonpos = argmax([x > 0 ? -Inf : x for x in evals[k,:]])
        push!(bval1, dot(rat_alphas[k,:], rat_sample[greatest_nonpos]) + 
            distances[greatest_nonpos])
        
        progress += 1
        @debug "Removing redundant half-spaces: $(round(progress/total * 100, digits=3))%   \r"    
    end
    
    @debug "\nFinding defining facets..."
    
    poly = polyhedron(hrep(rat_alphas, bval1), T(:exact))
    removehredundancy!(poly)
    
    if rep == :hrep
        @debug "Finding facets..."
        return hrep(poly)
    elseif rep == :vrep
        @debug "Finding vertices..."
        return vrep(poly)
    else
        @debug "Defaulting to polyhedron."
        return poly
    end
end

poly_frechet_set(sample, alphas; power=2, rep=:polyhedron, tol=1e-3) = poly_frechet_set(CDDLib.Library, sample, alphas, power=power, rep=rep, tol=tol)

poly_frechet_set (generic function with 2 methods)

## Examples

### Toy example: Fréchet mean for $L^\infty$-norm in $\mathbb{R}^2$

In [8]:
### Facets for the L-infinity norm
### Technically twice as long as strictly necessary
Linf_facets = [ 1  0 ;
               -1  0 ;
                0  1 ;
                0 -1 ]

sample = [ [0, 0], 
           [2, 2] ]

my_point = [7, 10]

println("Polyhedral distances from sample to $(my_point): ", 
    [poly_dist(pt, my_point, Linf_facets) for pt in sample])

println("Sum of polyhedral distances: ", 
    sum_of_poly_dist(my_point, sample, Linf_facets))

println("Sum of squared polyhedral distances: ", 
    sum_of_poly_dist(my_point, sample, Linf_facets, power=2))


Polyhedral distances from sample to [7, 10]: [10, 8]
Sum of polyhedral distances: 18
Sum of squared polyhedral distances: 164


In [9]:
@show poly_frechet(sample, Linf_facets)
poly_frechet_set(sample, Linf_facets; tol=1e-3) |> vrep

poly_frechet(sample, Linf_facets) = [1.000052213466546, 1.000052213466426]


InterruptException: InterruptException:

### Manual tropical Fréchet mean in $\mathbb{R}^3/\mathbb{R}\mathbf{1}$

In [10]:
Linf3_facets = [ -1   1  0;
                  1  -1  0;
                 -1   0  1;
                  1   0 -1;
                  0  -1  1;
                  0   1 -1 ]

sample2 = [ [0, 0, 0], 
            [0, 2, 4],
            [0, 5, 1] ]

@show poly_frechet(sample2, Linf3_facets, power=2) |> trop_normalize
poly_frechet_set(sample2, Linf3_facets, rep="vrep", tol=1e-3)

poly_frechet(sample2, Linf3_facets, power = 2) |> trop_normalize = [0.0, 1.9999999991413533, 1.0001319108600755]


Polyhedron CDDLib.Polyhedron{Rational{BigInt}}:
2-element iterator of HyperPlane{Rational{BigInt}, Vector{Rational{BigInt}}}:
 HyperPlane(Rational{BigInt}[-1, 1, 0], 2//1)
 HyperPlane(Rational{BigInt}[1, 0, -1], -1//1)

# Tropical Frèchet means

In [11]:
"""
Find the relevant facet normals in n dimensions for a tropical ball
"""
function trop_facets(n::Int64)
    result = zeros(Rational{Int64}, n * (n - 1), n)
    k = 1
    for i = 1:n
        for j = 1:n
            if i != j
                result[k, i] = 1//1
                result[k, j] = -1//1
                k += 1
            end
        end
    end
    return result
end

trop_facets

In [12]:
"""
Calculate the tropical distance between two vectors.
"""
function trop_dist(vec1, vec2)
    return maximum(vec1 - vec2) - minimum(vec1 - vec2)
end

trop_dist

In [13]:
"""
Calculate the sum of tropical distances between `ref` and the points in `sample`.
"""
function sum_of_trop_dist(ref, sample; power=1)
    return sum([trop_dist(pt, ref)^power for pt in sample])
end

sum_of_trop_dist

In [14]:
"""
Find one polyhedral Fréchet mean of a given sample.
The rows of `alphas` are the facet normals scaled to α⋅x = 1.
`power` gives the exponent of the distance before taking the sum.
"""
function trop_frechet(sample; power=2)
    dim = length(sample[1])
    alphas = trop_facets(dim)
    return poly_frechet(sample, alphas, power=power)
end

trop_frechet

In [15]:
"""
Find one polyhedral Fréchet mean of a given sample.
The rows of `alphas` are the facet normals scaled to α⋅x = 1.
`power` gives the exponent of the distance before taking the sum.
"""
function trop_frechet_set(sample; power=2, rep=:polyhedron, tol=1e-3)
    dim = length(sample[1])
    alphas = trop_facets(dim)
    return poly_frechet_set(sample, alphas, power=power, rep=rep, tol=tol)
end

trop_frechet_set

## Examples
### Toy example

In [16]:
sample = [[0,0,0], [0,4,1]]

my_point = [7, 10, 2]

println("Tropical distances: ", 
    [trop_dist(pt, my_point) for pt in sample])

println("Sum of tropical distances: ", 
    sum_of_trop_dist(my_point, sample))

println("Sum of squared tropical distances: ", 
    sum_of_trop_dist(my_point, sample, power=2))

Tropical distances: [8, 6]
Sum of tropical distances: 14
Sum of squared tropical distances: 100


In [17]:
num_FM = trop_frechet(sample) |> trop_normalize
@show num_FM
trop_frechet_set(sample, rep=:vrep, tol=1e-3)

num_FM = [0.0, 2.0000154234464373, 0.7004901999320469]


V-representation CDDGeneratorMatrix{Rational{BigInt}, GMPRational}:
2-element iterator of Vector{Rational{BigInt}}:
 Rational{BigInt}[-1, 1, 0]
 Rational{BigInt}[0, 2, 0],
1-element iterator of Line{Rational{BigInt}, Vector{Rational{BigInt}}}:
 Line(Rational{BigInt}[1, 1, 1])

### Example of Section 4.2. "Exact Quadratic Optimization"

In [18]:
sample = [[-3,0,0], [0,-6,0], [0,0,-12]]

num_FM = trop_frechet(sample) |> trop_normalize
@show num_FM
trop_frechet_set(sample, rep="vrep", tol=1e-3) |> vrep

num_FM = [0.0, -1.4387319974273893e-8, -1.0001294161599674]


V-representation CDDGeneratorMatrix{Rational{BigInt}, GMPRational}:
1-element iterator of Vector{Rational{BigInt}}:
 Rational{BigInt}[1, 1, 0],
1-element iterator of Line{Rational{BigInt}, Vector{Rational{BigInt}}}:
 Line(Rational{BigInt}[1, 1, 1])

In [19]:
trop_facets(3)

6×3 Matrix{Rational{Int64}}:
  1  -1   0
  1   0  -1
 -1   1   0
  0   1  -1
 -1   0   1
  0  -1   1

### Example 10 (Failure of Sturm's algorithm)

In [20]:
sample = [ [0, 0, 0], 
           [0, 2, 4],
           [0, 5, 1] ]

num_FM = trop_frechet(sample) |> trop_normalize
@show num_FM
trop_frechet_set(sample, rep="vrep", tol=1e-3)

num_FM = [0.0, 1.9999999991422408, 1.0001320211409572]


Polyhedron CDDLib.Polyhedron{Rational{BigInt}}:
2-element iterator of HyperPlane{Rational{BigInt}, Vector{Rational{BigInt}}}:
 HyperPlane(Rational{BigInt}[1, -1, 0], -2//1)
 HyperPlane(Rational{BigInt}[1, 0, -1], -1//1)

In [21]:
model = poly_frechet_model(sample, trop_facets(3), power=2) |> first
display(model)
constraints_string(MIME("text/plain"), model)

A JuMP Model
├ solver: Clarabel
├ objective_sense: MIN_SENSE
│ └ objective_function_type: AffExpr
├ num_variables: 6
├ num_constraints: 18
│ └ QuadExpr in MOI.GreaterThan{Float64}: 18
└ Names registered in the model
  └ :t, :x

18-element Vector{String}:
 "-x[1]² + 2 x[2]*x[1] - x[2]² + t[1] ≥ 0"
 "-x[1]² + 2 x[3]*x[1] - x[3]² + t[1] ≥ 0"
 "-x[1]² + 2 x[2]*x[1] - x[2]² + t[1] ≥ 0"
 "-x[2]² + 2 x[3]*x[2] - x[3]² + t[1] ≥ 0"
 "-x[1]² + 2 x[3]*x[1] - x[3]² + t[1] ≥ 0"
 "-x[2]² + 2 x[3]*x[2] - x[3]² + t[1] ≥ 0"
 "-x[1]² + 2 x[2]*x[1] - x[2]² - 4 x[1] + 4 x[2] + t[2] ≥ 4"
 "-x[1]² + 2 x[3]*x[1] - x[3]² - 8 x[1] + 8 x[3] + t[2] ≥ 16"
 "-x[1]² + 2 x[2]*x[1] - x[2]² - 4 x[1] + 4 x[2] + t[2] ≥ 4"
 "-x[2]² + 2 x[3]*x[2] - x[3]² - 4 x[2] + 4 x[3] + t[2] ≥ 4"
 "-x[1]² + 2 x[3]*x[1] - x[3]² - 8 x[1] + 8 x[3] + t[2] ≥ 16"
 "-x[2]² + 2 x[3]*x[2] - x[3]² - 4 x[2] + 4 x[3] + t[2] ≥ 4"
 "-x[1]² + 2 x[2]*x[1] - x[2]² - 10 x[1] + 10 x[2] + t[3] ≥ 25"
 "-x[1]² + 2 x[3]*x[1] - x[3]² - 2 x[1] + 2 x[3] + t[3] ≥ 1"
 "-x[1]² + 2 x[2]*x[1] - x[2]² - 10 x[1] + 10 x[2] + t[3] ≥ 25"
 "-x[2]² + 2 x[3]*x[2] - x[3]² + 8 x[2] - 8 x[3] + t[3] ≥ 16"
 "-x[1]² + 2 x[3]*x[1] - x[3]² - 2 x[1] + 2 x[3] + t[3] ≥ 1"
 "-x[2]² + 2 x[3]*x[2] - x[3]² + 8 

### Figure 1

In [22]:
sample = [ [0,  0, 8], 
           [0,  2, 4],
           [0,  5, 3],
           [0, 10, 2] ]

@show trop_frechet(sample) |> trop_normalize
P = trop_frechet_set(sample, tol=1e-3)

trop_frechet(sample) |> trop_normalize = [0.0, 3.205087304018976, 3.2050203078168154]


Polyhedron CDDLib.Polyhedron{Rational{BigInt}}:
1-element iterator of HyperPlane{Rational{BigInt}, Vector{Rational{BigInt}}}:
 HyperPlane(Rational{BigInt}[0, 1, -1], 0//1),
2-element iterator of HalfSpace{Rational{BigInt}, Vector{Rational{BigInt}}}:
 HalfSpace(Rational{BigInt}[1, -1, 0], -3//1)
 HalfSpace(Rational{BigInt}[-1, 1, 0], 4//1)

In [23]:
exact_FM = points(P) |> collect |> rand |> trop_normalize
@show exact_FM
trop_dist.(Ref(exact_FM), sample)

exact_FM = Rational{BigInt}[0, 3, 3]


4-element Vector{Rational{BigInt}}:
 8
 2
 2
 8

### Random points in high dimensional space

In [24]:
n = 20
m = n

rand_sample = [rand(1:20, n) for _ in 1:m]

20-element Vector{Vector{Int64}}:
 [1, 5, 5, 20, 6, 14, 20, 13, 19, 1, 13, 4, 8, 8, 19, 6, 17, 13, 20, 4]
 [20, 15, 6, 1, 20, 8, 12, 19, 12, 11, 13, 12, 8, 18, 3, 16, 18, 7, 6, 18]
 [2, 9, 12, 10, 1, 17, 9, 6, 3, 17, 19, 13, 4, 1, 19, 9, 6, 5, 10, 10]
 [15, 14, 6, 3, 13, 16, 10, 9, 16, 15, 12, 1, 2, 4, 15, 12, 5, 4, 11, 17]
 [10, 3, 18, 11, 12, 17, 2, 9, 10, 1, 14, 9, 14, 9, 14, 20, 16, 9, 16, 13]
 [2, 11, 15, 3, 10, 20, 12, 11, 9, 11, 6, 2, 19, 10, 3, 9, 2, 10, 12, 14]
 [5, 12, 10, 9, 17, 1, 19, 17, 17, 4, 8, 16, 10, 14, 6, 14, 15, 8, 20, 17]
 [9, 6, 13, 1, 16, 19, 5, 7, 2, 1, 5, 1, 16, 11, 5, 20, 11, 12, 11, 8]
 [9, 7, 13, 18, 11, 17, 6, 7, 4, 7, 15, 8, 14, 12, 3, 2, 11, 14, 1, 6]
 [14, 2, 13, 7, 15, 14, 1, 9, 8, 15, 19, 15, 5, 4, 9, 15, 2, 3, 3, 2]
 [10, 6, 7, 12, 14, 14, 7, 16, 4, 19, 11, 14, 17, 6, 2, 11, 15, 7, 10, 13]
 [17, 13, 12, 7, 2, 12, 5, 14, 12, 11, 20, 16, 1, 1, 20, 7, 11, 19, 20, 1]
 [1, 13, 3, 17, 15, 8, 6, 2, 17, 13, 9, 1, 6, 3, 13, 5, 17, 3, 20, 14]
 [13, 15, 8, 4, 5

In [25]:
@time trop_frechet(rand_sample) |> trop_normalize

  0.369399 seconds (3.81 M allocations: 293.948 MiB, 11.76% gc time)


20-element Vector{Float64}:
  0.0
  0.5523435986748666
  0.9999999976089882
  0.7499998696921821
  1.0000000026982683
  1.99999999630856
  0.9999999974340525
  0.9999999931824561
  1.3875358202138486
  1.0530598615332565e-9
  1.0001709066815536
 -9.417533419764368e-10
  1.0000000022933833
  1.0000000126270585
  1.000000000144027
  2.9999999966578237
 -4.244167683964406e-9
  0.9999999996372964
  1.9999999974126794
  1.9999999855203576

In [26]:
@time trop_frechet_set(rand_sample, rep="vrep", tol=1e-3)

  2.584861 seconds (13.15 M allocations: 384.377 MiB, 5.64% gc time)


Polyhedron CDDLib.Polyhedron{Rational{BigInt}}:
17-element iterator of HyperPlane{Rational{BigInt}, Vector{Rational{BigInt}}}:
 HyperPlane(Rational{BigInt}[1, 0, 0, -1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], -674//899)
 HyperPlane(Rational{BigInt}[1, 0, 0, 0, 0, -1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], -2//1)
 HyperPlane(Rational{BigInt}[1, 0, 0, 0, 0, 0, 0, -1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], -1//1)
 HyperPlane(Rational{BigInt}[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 0, 0, 0, 0, 0, 0], -1//1)
 HyperPlane(Rational{BigInt}[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 0, 0, 0, 0, 0], -1//1)
 HyperPlane(Rational{BigInt}[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 0, 0], 0//1)
 HyperPlane(Rational{BigInt}[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 0], -1//1)
 HyperPlane(Rational{BigInt}[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0], -2//1)
 HyperPlane(Rational{BigInt}[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 

### Big random sample in 3-space

In [27]:
n = 3

Random.seed!(50)

for m = 2:3n
    dim_vec = zeros(Int64, n+1)
    for _ = 1:100
        rand_sample = [rand(1:10, n) for _ in 1:m]
        try
            my_frech = trop_frechet_set(rand_sample, rep="hrep", tol=1e-3)
            dim_vec[dim(my_frech) + 1] += 1
        catch e
            println(rand_sample)
        end
    end
    println(m, " sample points ", dim_vec / sum(dim_vec))
end

[[5, 5, 9], [4, 6, 9]]
2 sample points [0.0, 0.26262626262626265, 0.7373737373737373, 0.0]
3 sample points [0.0, 0.6, 0.4, 0.0]
4 sample points [0.0, 0.88, 0.12, 0.0]
5 sample points [0.0, 0.93, 0.07, 0.0]
6 sample points [0.0, 0.97, 0.03, 0.0]
[[2, 4, 10], [3, 10, 2], [3, 2, 9], [1, 3, 3], [10, 6, 4], [6, 9, 1], [10, 9, 2]]
[[2, 7, 1], [10, 3, 10], [9, 10, 10], [1, 2, 4], [5, 6, 7], [4, 6, 1], [6, 9, 10]]
[[8, 9, 1], [8, 5, 10], [10, 3, 5], [9, 10, 9], [10, 7, 6], [7, 3, 7], [1, 1, 6]]
7 sample points [0.0, 1.0, 0.0, 0.0]
8 sample points [0.0, 1.0, 0.0, 0.0]
9 sample points [0.0, 1.0, 0.0, 0.0]


## Application: Phylogenetic trees

In [28]:
using JSON3
using DataFrames

# Function to read the JSON file and convert to a list of matrices
function read_and_convert_json(file_path::String)
    # Read the JSON file
    json_data = JSON3.read(file_path)
    
    # Extract elements from the nested arrays
    elements = [x[1] for x in json_data]
    elements = rationalize.(10000 * elements, tol=1e-2)
    
    # Convert elements into matrices
    num_elements = length(elements)
    matrices = []
    
    for i in 1:64:num_elements
        # Get the next 64 elements
        matrix_elements = elements[i:min(i+63, num_elements)]
        
        # Convert to an 8x8 matrix if there are 64 elements, otherwise create a smaller matrix
        matrix_size = length(matrix_elements)
        sqrt_size = Int(sqrt(matrix_size))
        push!(matrices, reshape(matrix_elements, sqrt_size, sqrt_size))
    end
    
    return matrices
end

# Read and convert the JSON file
file_path = "all_matrices.json"
matrices = read_and_convert_json(file_path)
taxa = ["Tg", "Et", "Cp", "Ta", "Bb", "Tt", "Pv", "Pf"]

8-element Vector{String}:
 "Tg"
 "Et"
 "Cp"
 "Ta"
 "Bb"
 "Tt"
 "Pv"
 "Pf"

In [29]:
"""
Take a matrix of pairwise distances between taxa and returns the cophenetic vector.
"""
function cophenetic_from_distance(pairwise)
    n = size(pairwise, 1)
    coph = [pairwise[i, j] for i in 1:n-1 for j in i+1:n]
    return coph
end

cophenetic_from_distance

In [30]:
"""
Check if a distance matrix defines a phylogenetic tree
"""
function is_phylogenetic_tree(D)
    n = size(D, 1)
    
    # Check if the matrix is symmetric and non-negative
    for i in 1:n
        for j in i:n
            if D[i, j] != D[j, i] || D[i, j] < 0
                return false
            end
        end
    end

    # Check the four-point condition
    for i in 1:n-3
        for j in i+1:n-2
            for k in j+1:n-1
                for l in k+1:n
                    # Calculate distances
                    D_ij_kl = D[i, j] + D[k, l]
                    D_ik_jl = D[i, k] + D[j, l]
                    D_il_jk = D[i, l] + D[j, k]
                    
                    # Check the four-point condition
                    if !(D_ij_kl >= D_ik_jl && D_ij_kl >= D_il_jk) &&
                       !(D_ik_jl >= D_ij_kl && D_ik_jl >= D_il_jk) &&
                       !(D_il_jk >= D_ij_kl && D_il_jk >= D_ik_jl)
                        return false
                    end
                end
            end
        end
    end
    
    return true
end

is_phylogenetic_tree

In [31]:
"""
Check if a distance matrix defines an ultrametric tree
"""
function is_ultrametric_tree(D)
    n = size(D, 1)
    
    # Check if the matrix is symmetric and non-negative
    for i in 1:n
        for j in i:n
            if D[i, j] != D[j, i] || D[i, j] < 0
                return false
            end
        end
    end

    # Check the ultrametric condition
    for i in 1:n-2
        for j in i+1:n-1
            for k in j+1:n
                # Calculate distances
                Dij = D[i, j]
                Dik = D[i, k]
                Djk = D[j, k]
                
                # Check if the largest distance is attained at least twice
                if !(Dij <= max(Dik, Djk) && Dik <= max(Dij, Djk) && Djk <= max(Dij, Dik))
                    return false
                end
            end
        end
    end
    
    return true

end

is_ultrametric_tree

In [32]:
println("All phylogenetic: ", all([is_phylogenetic_tree(matrices[i]) for i = 1:268]))
println("All ultrametric: ", all([is_ultrametric_tree(matrices[i]) for i = 1:268]))

All phylogenetic: true
All ultrametric: false


In [35]:
coph_vecs = [cophenetic_from_distance(mat) for mat in matrices]
phylo_frech = trop_frechet_set(coph_vecs, rep="hrep")

InterruptException: InterruptException:

In [ ]:
vrep(phylo_frech)

In [34]:
@time trop_frechet(coph_vecs)

  6.946808 seconds (79.28 M allocations: 5.832 GiB, 11.30% gc time, 0.04% compilation time)


28-element Vector{Float64}:
 -0.0076861671948035
 -0.00768606923026732
 -0.007686279028993909
 -0.007686061716270971
 -0.007686216799891854
 -0.0076861889394709984
 -0.007686027372466219
 -0.007686054728709499
 -0.0076862927980135744
 -0.007686092103339983
  ⋮
 -0.007701168321674087
 -0.007687357882420762
 -0.007686128126366775
 -0.007686499659441921
 -0.007686313938359478
 -0.007686038674918775
 -0.007687437677703947
 -0.007686452817458049
 -0.007686530141153633

In [35]:
length(coph_vecs)

268

In [36]:
dim(phylo_frech)

24

In [37]:
N = 10
M = 100
Random.seed!(123)

dimensions = [[] for _ = 3:N]
for n = 3:N
    for m = 2:M
        sample = [Rational.(rand(0:10000, n)) for _ in 1:m]
        push!(dimensions[n-2], dim(trop_frechet_set(sample, rep="hrep")))
        println("m = ", m, "; n = ", n, " done!")
    end
end

dimensions

m = 2; n = 3 done!
m = 3; n = 3 done!
m = 4; n = 3 done!
m = 5; n = 3 done!
m = 6; n = 3 done!
m = 7; n = 3 done!
m = 8; n = 3 done!
m = 9; n = 3 done!
m = 10; n = 3 done!
m = 11; n = 3 done!
m = 12; n = 3 done!
m = 13; n = 3 done!
m = 14; n = 3 done!
m = 15; n = 3 done!
m = 16; n = 3 done!
m = 17; n = 3 done!
m = 18; n = 3 done!
m = 19; n = 3 done!
m = 20; n = 3 done!
m = 21; n = 3 done!
m = 22; n = 3 done!
m = 23; n = 3 done!
m = 24; n = 3 done!
m = 25; n = 3 done!
m = 26; n = 3 done!
m = 27; n = 3 done!
m = 28; n = 3 done!
m = 29; n = 3 done!
m = 30; n = 3 done!
m = 31; n = 3 done!
m = 32; n = 3 done!
m = 33; n = 3 done!
m = 34; n = 3 done!
m = 35; n = 3 done!
m = 36; n = 3 done!
m = 37; n = 3 done!
m = 38; n = 3 done!
m = 39; n = 3 done!
m = 40; n = 3 done!
m = 41; n = 3 done!
m = 42; n = 3 done!
m = 43; n = 3 done!
m = 44; n = 3 done!
m = 45; n = 3 done!
m = 46; n = 3 done!
m = 47; n = 3 done!
m = 48; n = 3 done!
m = 49; n = 3 done!
m = 50; n = 3 done!
m = 51; n = 3 done!
m = 52; 

8-element Vector{Vector{Any}}:
 [2, 1, 2, 1, 1, 1, 1, 1, 1, 1  …  1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
 [3, 2, 1, 2, 1, 2, 1, 1, 1, 1  …  1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
 [4, 3, 3, 3, 2, 1, 2, 1, 2, 1  …  1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
 [5, 5, 4, 4, 3, 4, 1, 2, 2, 3  …  1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
 [7, 7, 6, 3, 5, 4, 2, 4, 4, 4  …  1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
 [7, 8, 5, 4, 6, 4, 5, 6, 2, 1  …  1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
 [8, 7, 8, 7, 6, 5, 6, 5, 3, 4  …  1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
 [9, 9, 10, 6, 7, 6, 4, 5, 5, 6  …  1, 1, 1, 1, 1, 1, 1, 1, 1, 1]

In [38]:
using Plots

# Example data: categories and their respective proportions in different groups
categories = ["Category 1", "Category 2", "Category 3"]

proportional_dimensions = [dim_list / M for dim_list in dimensions]
data = hcat(proportional_dimensions...)

# Create the proportional bar chart
bar(data, label=1:M, legend=:topright, title="Proportional Bar Chart", xlabel="Groups", ylabel="Proportion", bar_width=0.7, lw=0, series_annotations=transpose([group1 group2 group3]))

# Save the plot to a file
savefig("proportional_bar_chart.png")

# Display the plot
display(plot)

UndefVarError: UndefVarError: `group1` not defined

In [39]:
for thing in dimensions
    println(thing)
    println()
end

Any[2, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]

Any[3, 2, 1, 2, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]

Any[4, 3, 3, 3, 2, 1, 2, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]

Any[5, 5, 4, 4, 3, 4, 1, 2, 2, 3, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 